- when: "is_compute and configure_and_create_gpu_instances"
  block:
    - set_fact:
        gpu_pci_vendor_and_product_id: "{{gpu_pci_vendor_id}}:{{gpu_pci_product_id}}"
    - name: "Make sure that GPU PCI is being used by vfio-pci"
      script: "../data/check-pci-are-in-use-by-vfio-pci.py \"{{gpu_pci_vendor_and_product_id}}\""

    - name: "Check if iommu already enabled"
      become: true
      ignore_errors: "{{ ignore_iommu_not_detected_error }}"
      shell: >-
        cat /proc/cmdline | grep iommu
      register: iommu_enabled
    - name: "Check if iommu already enabled (2)"
      become: true
      ignore_errors: "{{ ignore_iommu_not_detected_error }}"
      shell: >-
        virt-host-validate | grep "iommu.*PASS" -i
      register: iommu_enabled_2

    - set_fact:  # TODO rename misleading variable name. It should be iommu_not_enabled and iommu_not_enabled_2
        iommu_enabled: "{{ iommu_enabled.stdout | length == 0 }}"
        iommu_enabled_2: "{{ iommu_enabled_2.stdout | length == 0 }}"
    - debug:
        var: ignore_iommu_not_detected_error
    - debug:
        var: iommu_enabled
    - debug:
        var: iommu_enabled_2
    - fail:
        msg: "Please enable iommu by append either intel_iommu=on or amd_iommu=on to the GRUB_CMDLINE_LINUX_DEFAULT in /etc/default/grub"
      when: "iommu_enabled and iommu_enabled_2 and not ignore_iommu_not_detected_error"

# sudo nano /etc/nova/nova.conf