- set_fact:
    leftover_dnsmasq_path: "/opt/stack/devstack/dnsmasq"
- name: "Remove leftover dnsmasq folder" # Unstack.sh/Clean.sh doesn't remove dnsmasq file
  file:
    path: "{{ leftover_dnsmasq_path }}"
    state: absent

- set_fact:
    leftover_virtualBMC_path: "/opt/stack/.vbmc/node-0"

- name: "Remove leftover virtualBMC node-0"
  file:
    path: "{{ leftover_virtualBMC_path }}"
    state: absent
