# - when: is_controller
#   block:
    # - name: "copy Dockerfile to server"
    #   copy:
    #     content: |
    #       FROM nvidia/cuda:12.4.1-cudnn-runtime-ubuntu20.04

    #       RUN apt-get update && apt-get install -y openssh-server
    #       RUN mkdir /var/run/sshd
    #       RUN echo 'root:1122' | chpasswd
    #       # SSH login fix. Otherwise user is kicked off after login
    #       RUN sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config
    #       RUN sed 's@session\s*required\s*pam_loginuid.so@session optional pam_loginuid.so@g' -i /etc/pam.d/sshd
    #       EXPOSE 22
    #       # Start SSH server

    #       CMD ["/usr/sbin/sshd", "-D"]
    #     dest: "{{base_path}}/Dockerfile"
    #     mode: "0777"

    # - name: "copy create_zun_container.py to server"
    #   template:
    #     src: "../data/create_zun_container.py"
    #     dest: "{{base_path}}/create_zun_container.py"
    #     mode: "0777"

    # - name: "running create_zun_container.py to create GPU zun container"
    #   command: "{{base_path}}/create_zun_container.py \"{{admin_password}}\" gpu"
    #   register: create_zun_container_result
    #   when: configure_and_create_gpu_instances
    # - debug:
    #     var: create_zun_container_result.stdout

#  zun run -i --name test --security-group 9d58e831-b25a-473c-b457-bc53073475ff nvidia/cuda:12.4.1-cudnn-runtime-ubuntu20.04 /bin/bash