# asia-northeast3-c
- name: Main
  hosts: all
  become: True
  vars:
    base_path: /opt/stack
    admin_password: "1122"
    OS_PROJECT_NAME: "demo"  # I think it's the default automatically-created project by the devstack
    parent_directory: "{{ inventory_dir | dirname }}"
    ssh_key_destination_path: "/opt/stack/.ssh/id_ed25519"
    force_reinstall: true

    # Coba jalanin `ifconfig` di controller-node, dan cek Netmask dari physical interfacenya.
    # Kalau netmasknya /32, isi field ini dengan subnet yang tidak intersect dengan subnet2 yang ada
    # di komputer host (both compute maupun controller node)
    # Dengan begitu nanti dari CONTROLLER node kita bisa ping ke floating IP (tp untuk saat ini msh blom bisa SSH)
    devstack_floating_ip_range: "10.101.10.0/24"
  tasks:
    - debug:
        msg: "python3 ./data/convert-all-crlf-to-lf.py \"{{parent_directory}}\""
    - name: convert all ansible-related file to LF end-of-line
      command: "python3 ./data/convert-all-crlf-to-lf.py \"{{parent_directory}}\" 2>&1"
      delegate_to: "localhost"
      register: result
#    - debug:
#        var: result
    - import_tasks: tasks-openstack-core/01-check-if-devstack-successfully-installed.yml
    - import_tasks: tasks-openstack-core/02-get-ip-addr-information.yml
    - any_errors_fatal: "{{ is_controller }}"
      block:
        - import_tasks: tasks-openstack-core/04-allow-become_user-stack.yml
        - import_tasks: tasks-openstack-core/05-upload-ssh-key.yml
        - remote_user: stack
          become_user: stack
          become_method: sudo
          block:
            - import_tasks: tasks-openstack-core/06-assert-logged-in-to-the-correct-user.yml
            - import_tasks: tasks-openstack-core/07-async-start-downloading-needed-linux-images.yml
            - when: "not devstack_already_installed_successfully"
              block:
                - import_tasks: tasks-openstack-core/08-prepare-installation-script.yml
                - import_tasks: tasks-openstack-core/09-setup-devstack-configuration.yml
                - import_tasks: tasks-openstack-core/10-uninstall-devstack.yml
                - import_tasks: tasks-openstack-core/11-install-devstack.yml
            - import_tasks: tasks-openstack-core/12-fix-communication-problem-between-ext-network-and-neutron.yml
            - import_tasks: tasks-openstack-core/12-setup-startup-script.yml
            - import_tasks: tasks-configure-nova/01-installation-finalization-step.yml
            - import_tasks: tasks-openstack-core/12-insert-downloaded-linux-images-to-openstack.yml
            - import_tasks: tasks-configure-nova/02-create-nova-instance.yml

