# asia-northeast3-c
- name: Main
  hosts: all
  become: True
  vars:
    base_path: /opt/stack
    admin_password: "1122"
    OS_PROJECT_NAME: "demo"  # I think it's the default automatically-created project by the devstack
    parent_directory: "{{ inventory_dir | dirname }}"
    ssh_key_destination_path: "/opt/stack/.ssh/id_ed25519"
    force_reinstall: false

    # Isi dengan subnet yang tidak intersect dengan subnet2 yang ada di komputer host (both compute maupun controller node)
    # Dengan begitu nanti dari CONTROLLER node kita bisa ping ke floating IP
    # Tapi untuk saat ini masih belum bisa SSH pake floating-ip
    devstack_floating_ip_range: "10.101.10.0/24"

    devstack_q_floating_allocation_pool_start: "10.101.10.100"  # should be subset of devstack_floating_ip_range
    devstack_q_floating_allocation_pool_end: "10.101.10.254"  # should be subset of devstack_floating_ip_range
  tasks:
    - debug:
        msg: "python3 ./data/convert-all-crlf-to-lf.py \"{{parent_directory}}\""
    - name: convert all ansible-related file to LF end-of-line
      command: "python3 ./data/convert-all-crlf-to-lf.py \"{{parent_directory}}\" 2>&1"
      delegate_to: "localhost"
      register: result
    - debug:
        var: result
    - import_tasks: ./tasks/check-if-devstack-successfully-installed.yml
    - import_tasks: ./tasks/get-ip-addr-information.yml
    - import_tasks: ./tasks/insert_new_veth.yml
    - import_tasks: ./tasks/allow-become_user-stack.yml
    - import_tasks: ./tasks/upload-ssh-key.yml
    - remote_user: stack
      become_user: stack
      become_method: sudo
      block:
        - import_tasks: ./tasks/assert-logged-in-to-the-correct-user.yml
        - import_tasks: ./tasks/async-start-downloading-needed-linux-images.yml
        - when: "not devstack_already_installed_successfully"
          block:
            - import_tasks: ./tasks/prepare-installation-script.yml
            - import_tasks: ./tasks/setup-devstack-configuration.yml
            - import_tasks: ./tasks/uninstall-devstack.yml
            - import_tasks: ./tasks/install-devstack.yml
        - import_tasks: ./tasks/installation-finalization-step.yml
        - import_tasks: ./tasks/insert-downloaded-linux-images-to-openstack.yml

