# asia-northeast3-c
- name: Main
  hosts: all
  become: True
  vars:
    base_path: /opt/stack
    admin_password: "1122"
  tasks:
    - import_tasks: ./tasks/check-if-devstack-successfully-installed.yml
    - debug:
        var: devstack_already_installed_successfully
    - import_tasks: ./tasks/get-ip-addr-information.yml
    - when: "not devstack_already_installed_successfully"
      block:  # this block is idempotent. This is done just to increase performance
        - import_tasks: ./tasks/create-user-for-openstack.yml

        - name: "allow to run ansible become_user: stack"  # see https://stackoverflow.com/a/56379678/7069108
          apt:
            update_cache: yes
            name:
              - acl

    - remote_user: stack
      become_user: stack
      become_method: sudo
      block:
        - import_tasks: ./tasks/assert-logged-in-to-the-correct-user.yml

        - when: "not devstack_already_installed_successfully"
          block:
            - import_tasks: ./tasks/prepare-installation-script.yml
            - import_tasks: ./tasks/setup-devstack-configuration.yml
            - import_tasks: ./tasks/uninstall-devstack.yml
            - import_tasks: ./tasks/install-devstack.yml
#    - become: true
#      block:
        - import_tasks: ./tasks/async-start-downloading-needed-linux-images.yml
        - import_tasks: ./tasks/installation-finalization-step.yml
        - import_tasks: ./tasks/insert-downloaded-linux-images-to-openstack.yml

