# asia-northeast3-c
- name: Main
  hosts: all
  become: True
  vars:
    base_path: /opt/stack
    admin_password: "1122"
    OS_PROJECT_NAME: "demo"  # I think it's the default automatically-created project by the devstack
    parent_directory: "{{ inventory_dir | dirname }}"
  tasks:
    - name: convert all ansible-related file to LF end-of-line
      command: "python3 ./data/convert-all-crlf-to-lf.py \"{{parent_directory}}\""
      delegate_to: "localhost"
    - import_tasks: ./tasks/check-if-devstack-successfully-installed.yml
    - import_tasks: ./tasks/get-ip-addr-information.yml
    - import_tasks: ./tasks/allow-become_user-stack.yml

    - remote_user: stack
      become_user: stack
      become_method: sudo
      block:
        - import_tasks: ./tasks/assert-logged-in-to-the-correct-user.yml
        - import_tasks: ./tasks/async-start-downloading-needed-linux-images.yml
        - when: "not devstack_already_installed_successfully"
          block:
            - import_tasks: ./tasks/prepare-installation-script.yml
            - import_tasks: ./tasks/setup-devstack-configuration.yml
            - import_tasks: ./tasks/uninstall-devstack.yml
            - import_tasks: ./tasks/install-devstack.yml
        - import_tasks: ./tasks/installation-finalization-step.yml
        - import_tasks: ./tasks/insert-downloaded-linux-images-to-openstack.yml

