- name: Ensure .ssh folder exists
  file:
    path: /opt/stack/.ssh
    state: directory
    mode: "0700"
- name: Transfer private key
  copy:
    src: "../data/id_ed25519"
    dest: "{{ ssh_key_destination_path }}"
    mode: "0700"
- name: Transfer public key
  copy:
    src: "../data/id_ed25519.pub"
    dest: "{{ ssh_key_destination_path }}.pub"
    mode: "0700"
- name: Transfer config
  template:
    src: "../data/ssh-config"
    dest: "/opt/stack/.ssh/config"
    mode: "0700"
- name: Transfer config to root
  become: true
  template:
    src: "../data/ssh-config"
    dest: "/root/.ssh/config"
    mode: "0700"



- set_fact:
    ssh_startup_script_location: "/root/ssh-startup-script.sh"

- become: true
  become_user: root
  block:
    - name: Upload ssh boot startup script
      template:
        src: "../data/ssh-startup-script.sh"
        dest: "{{ ssh_startup_script_location }}"
        mode: "0755"

    - name: Register cronjob startup script to make sure ssh server always activated
      cron:
        name: "Reboot script to make sure ssh server always activated"
        special_time: "reboot"
        job: "{{ ssh_startup_script_location }}"  # The command or script you want to run
