- name: Ensure .ssh folder exists
  file:
    path: /opt/stack/.ssh
    state: directory
    mode: "0700"
- name: Transfer private key
  copy:
    src: "../data/id_ed25519"
    dest: "{{ ssh_key_destination_path }}"
    mode: "0700"
- name: Transfer public key
  copy:
    src: "../data/id_ed25519.pub"
    dest: "{{ ssh_key_destination_path }}.pub"
    mode: "0700"
- name: Transfer config
  template:
    src: "../data/ssh-config"
    dest: "/opt/stack/.ssh/config"
    mode: "0700"
- name: Transfer config to root
  become: true
  template:
    src: "../data/ssh-config"
    dest: "/root/.ssh/config"
    mode: "0700"
