- name: copy local.conf to server
  template:
    src: "../data/{{ node_type }}-local.conf"
    dest: ~/devstack/local.conf
- when: is_controller
  block:
    - name: copy local.sh to server
      template:
        src: "../data/{{ node_type }}-local.sh"
        dest: ~/devstack/local.sh
        mode: "0777"