# asia-northeast3-c
- name: Main
  hosts: controller_instance
  become: True
  vars:
    base_path: /home/root

  tasks:
    - name: ensure base_path is exists
      command: "mkdir -p {{ base_path }}"
    - name: install keystone
      import_role:
        name: "../roles/keystone"