- name: Main
  hosts: all
  become: True
  vars:
    base_path: ~
    local_idle_shutdown: "./data/idle-shutdown.sh"
    idle_shutdown: "{{ base_path }}/idle-shutdown.sh"
  tasks:
    - import_tasks: ../install_dos2unix.yaml
    - name: convert script to linux just in case
      command: "dos2unix \"{{ local_idle_shutdown }}\""
      delegate_to: localhost
    - name: copy script
      copy:
        src: "{{ local_idle_shutdown }}"
        dest: "{{ idle_shutdown }}"
    - name: chmod script
      file:
        path: "{{ idle_shutdown }}"
        state: file
        owner: root
        group: root
        mode: 0777
    - name: Install CPU-usage reader
      apt:
        update_cache: yes
        name:
          - bc
    - name: update cronjob
      become: false
      cron:
        name: "Autostart idle script"
        special_time: "reboot"
        job: "{{ idle_shutdown }}"  # The command or script you want to run
    - name: Reboot
      reboot:
        msg: "rebooting"
