- import_tasks: ./install_xorg_headless_virtual_display.yaml


### TODO migrate from phoronix to direct apt-get installation


- name: "install libpng16-16"
  apt:
    update_cache: yes
    name:
      - libpng16-16

- name: install phoronix glmark2
  command: "env DISPLAY=:1 ./phoronix-test-suite install {{ glmark2_version }} 2>&1"
  become: true
  args:
    chdir: "{{ phoronix_folder }}"


- name: run glmark2 benchmark
  async: 10000
  poll: 5
  become: true
  expect:
    timeout: 670
    command: "{{ prime_run }} env DISPLAY=:1 {{ phoronix_test_suite }} benchmark glmark2 2>&1"
    responses:
      'Resolution:': 4  # 1280 x 960
      'Would you like to save these test results': 'n'
  register: glmark2_benchmark_result
- set_fact:
    cleaned_glmark2_benchmark_result: "{{ glmark2_benchmark_result.stdout | regex_replace('\x1B\\[[0-9;]*[mK]', '') }}"
- name: write glmark2 benchmark stdout logs
  delegate_to: localhost
  copy:
    content: "{{ cleaned_glmark2_benchmark_result }}"
    dest: temp/glmark2_benchmark_result.txt