
- name: "run namd benchmark {{benchmark_batch_number}}"
  async: 10000
  poll: 5
  become: true
  expect:
    # average of 29 samples, each samples take 25.79310344827586 seconds. Total at least 14 mins for 30 tests
    timeout: 800
    command: "{{ prime_run }} env FORCE_TIMES_TO_RUN=5 DISPLAY=:0 {{ phoronix_test_suite }} benchmark {{ namd_version }} 2>&1"
    responses:
      'Would you like to save these test results': 'n'
  register: namd_benchmark_result
  retries: 20
  delay: 5
  until: "namd_benchmark_result.rc != 0 and 'E: FATAL ERROR' not in namd_benchmark_result.stdout"

- debug:
    msg: "{{namd_benchmark_result.rc != 0}}"
- debug:
    msg: "{{'fatal error' not in namd_benchmark_result.stdout.lower()}}"
- debug:
    msg: "{{namd_benchmark_result.stdout.lower()}}"

- set_fact:
    cleaned_namd_benchmark_result: "{{ namd_benchmark_result.stdout | regex_replace('\x1B\\[[0-9;]*[mK]', '') }}"
- name: "write namd benchmark logs {{benchmark_batch_number}}"
  delegate_to: localhost
  copy:
    content: "{{ cleaned_namd_benchmark_result }}"
    dest: "{{benchmark_result_folder}}/namd_benchmark_result_{{benchmark_batch_number}}.txt"
