- block:
    - import_tasks: ./install_xorg_headless_virtual_display.yaml
  rescue:
    - debug:
        msg: "Error install_xorg_headless_virtual_display.yaml, trying to purge nvidia-* and reboot"
    - name: "purging nvidia-*"
      command: "sudo apt-get remove --purge nvidia-* -y"
    - name: "sudo apt autoremove -y"
      command: "sudo apt autoremove -y"
    - name: Reboot
      reboot:
        msg: "rebooting"
    - import_tasks: ./install_xorg_headless_virtual_display.yaml  # retry once again


### TODO migrate from phoronix to direct apt-get installation


- name: "install libpng16-16"
  apt:
    update_cache: yes
    name:
      - libpng16-16

# `sudo ./prime-run env DISPLAY=:1 glmark2`
- name: run Xorg Display Server
  command: "Xorg :1"
  become: true
  async: true
  poll: 0

- name: Perform Glmark2 benchmark
  include_tasks: ./benchmark_glmark2_loop_body.yaml
  loop: "{{ ['1920x1080', '1366x768', '360x800', '192x108'] }}"
  loop_control:
    loop_var: benchmark_resolution

