- name: Mark PHP as installed
  command: "touch \"{{ base_path }}/php_is_installed\""
  args:
    creates: "{{ base_path }}/php_is_installed"
- debug:
    var: result
- name: copy prime-run
  copy:
    src: "{{ local_prime_run }}"
    dest: "{{ prime_run }}"
- name: chmod prime-run
  file:
    path: "{{ prime_run }}"
    state: file
    owner: root
    group: root
    mode: 0777
