- name: "install lspci"
  apt:
    update_cache: yes
    name:
      - pciutils
- name: "Getting list of connected NVIDIA GPU / hardware"
  shell: "lspci | (grep -i nvidia || true)"
  register: lspci_assert_nvidia_exists
- debug:
    msg: "{{ lspci_assert_nvidia_exists }}"
- name: "Assert NVIDIA GPU Hardware is connected / detected"
  assert:
    that:
      - lspci_assert_nvidia_exists.stdout is defined
      - lspci_assert_nvidia_exists.stdout != ""
    fail_msg: "NVIDIA GPU Hardware is not detected"


### TODO disable nouveau if exists (https://docs.kinetica.com/7.1/install/nvidia_deb/)


#- name: "install nvcc (CUDA)"
#  apt:
#    update_cache: yes
#    name:
#      - xserver-xorg-video-nvidia-525
#      - libnvidia-cfg1-525

#- name: "install In-memory/buffer display to simulate display monitor (subsitute for Nvidia Xorg server)"
#  apt:
#    update_cache: yes
#    name:
#      - xvfb
#
#- name: run Display Server
#  command: "Xvfb :1 -screen 0 1024x768x16"
#  async: true
#  poll: 0

- name: "install nvcc (CUDA)"
  apt:
    update_cache: yes
    name:
      - xauth
      - xorg
      - openbox


- name: "Run nvidia.nvidia_driver Role"
  import_role:
    name: nvidia.nvidia_driver
  vars:
    nvidia_driver_skip_reboot: no
#    nvidia_driver_package_version: "525.147.05"
    nvidia_driver_persistence_mode_on: yes


- name: "install nvcc (CUDA)"
  apt:
    update_cache: yes
    name:
      - nvidia-cuda-toolkit

#- name: "Install dependencies"
#  shell: |
#    sudo apt-get -y install linux-headers-$(uname -r) make gcc-4.8
#    sudo apt-get -y install acpid dkms
#- name: "Close X Server"
#  command: "sudo ps aux | grep \"lightdm|gdm|kdm\""
