### See https://linuxhint.com/install-nvidia-gpu-drivers-headless-ubuntu-server-22-04-lts/
### and https://www.cyberciti.biz/faq/ubuntu-linux-install-nvidia-driver-latest-proprietary-driver/
### and https://askubuntu.com/a/463000/1058660 / https://askubuntu.com/questions/453109/add-fake-display-when-no-monitor-is-plugged-in
###

## Seems to successfully run `sudo ./prime-run env DISPLAY=:1 glmark2`
## Tapi belum uji coba complete-reset untuk uji coba ansible-nya

- name: "apt install aptitude, more intelligent version of apt-get"
  apt:
    name:
      - aptitude


- name: "xserver-xorg-video-nvidia-{{nvidia_driver_version}}, libnvidia-cfg1-{{nvidia_driver_version}}"
  command: >-
    aptitude install xserver-xorg-video-nvidia-{{nvidia_driver_version}} libnvidia-cfg1-{{nvidia_driver_version}}
  become: true
  when: "install_nvidia_and_nvcc_drivers"



- name: "nvidia-driver-{{nvidia_driver_version}}, nvidia-dkms-{{nvidia_driver_version}}"
  command: >-
    aptitude install nvidia-driver-{{nvidia_driver_version}} nvidia-dkms-{{nvidia_driver_version}}
  become: true
  when: "install_nvidia_and_nvcc_drivers"

- name: "nvidia-driver-{{nvidia_driver_version}}-server"
  command: >-
    aptitude install nvidia-driver-{{nvidia_driver_version}}-server
  become: true
  when: "install_nvidia_and_nvcc_drivers"


- name: "xserver-xorg-video-dummy, glmark2"
  apt:
    name:
#      - xserver-xorg-video-dummy
      - xvfb
      - glmark2
