- name: "install lspci"
  apt:
    update_cache: yes
    name:
      - pciutils
- name: "Getting list of connected NVIDIA GPU / hardware"
  shell: "lspci | (grep -i nvidia || true)"
  register: lspci_assert_nvidia_exists
- debug:
    msg: "{{ lspci_assert_nvidia_exists }}"
- name: "Assert NVIDIA GPU Hardware is connected / detected"
  assert:
    that:
      - lspci_assert_nvidia_exists.stdout is defined
      - lspci_assert_nvidia_exists.stdout != ""
    fail_msg: "NVIDIA GPU Hardware is not detected"


### TODO disable nouveau if exists (https://docs.kinetica.com/7.1/install/nvidia_deb/)




- apt:
    update_cache: yes
    name:
      - xauth
      - xorg
      - openbox

- name: register status of ~/nvidia_driver_is_installed
  stat:
    path: "{{ base_path }}/nvidia_driver_is_installed"
  register: nvidia_driver_is_installed


- name: "Run nvidia.nvidia_driver Role"
  import_role:
    name: nvidia.nvidia_driver
  vars:
    nvidia_driver_skip_reboot: no
#    nvidia_driver_package_version: "525.147.05"
    nvidia_driver_persistence_mode_on: yes
  when: "not nvidia_driver_is_installed.stat.exists"


- name: Mark PHP as installed
  command: "touch \"{{ base_path }}/nvidia_driver_is_installed\""
  when: "not nvidia_driver_is_installed.stat.exists"


# instead of installing in /usr/local/cuda, it will install in various folder (see dpkg -L nvidia-cuda-toolkit | grep include)
# which will make cudnn's assertion error (sudo make clean && sudo make at cudnn_samples_v8/mnistCUDNN)
# So we need to create symlink
- name: "install nvcc (CUDA)"
  apt:
    update_cache: yes
    name:
      - nvidia-cuda-toolkit

- name: "install libfreeimage"  # for cudnn_samples_v8/mnistCUDNN
  apt:
    update_cache: yes
    name:
      - libfreeimage3
      - libfreeimage-dev

- file:
    path: "/usr/local/cuda"
    state: directory

# dpkg -L nvidia-cuda-toolkit | grep include
# To fix missing /usr/local/cuda/include/cuda.h
- name: Create symbolic link to fix cudnn
  file:
    src: "/usr/include"
    dest: "/usr/local/cuda/include"
    state: link

# dpkg -L nvidia-cuda-toolkit | grep bin
# To fix missing /usr/local/cuda/bin/nvcc
- name: Create symbolic link to fix cudnn (2)
  file:
    src: "/usr/bin"
    dest: "/usr/local/cuda/bin"
    state: link



#- name: "Install dependencies"
#  shell: |
#    sudo apt-get -y install linux-headers-$(uname -r) make gcc-4.8
#    sudo apt-get -y install acpid dkms
#- name: "Close X Server"
#  command: "sudo ps aux | grep \"lightdm|gdm|kdm\""
