# asia-northeast3-c
- name: Main
  hosts: id_ed25519
  become: True
  vars:
    base_path: /home/root
    local_prime_run: "./scripts/prime-run"
    prime_run: "{{ base_path }}/prime-run"
    phoronix_folder: "{{ base_path }}/phoronix"
    phoronix_test_suite: "{{ phoronix_folder }}/phoronix-test-suite"

    glmark2_version: 'glmark2-1.4.0'
    namd_version: 'namd-cuda-1.1.1'
    pytorch_phoronix_test_version: "pytorch-1.0.1"

    ### USER CONFIGURABLE VARS. See README.md
    distro: "ubuntu2004"
    arch: "x86_64"

  tasks:
    - name: ensure base_path is exists
      command: "mkdir -p {{ base_path }}"
    - name: Perform Benchmark
      import_tasks: perform_benchmark.yaml