# asia-northeast3-c
- name: Main
  hosts: gcp
  become: True
  vars:
    parent_directory: "{{ inventory_dir | dirname }}"
    base_path: /home/root
    local_prime_run: "./scripts/prime-run"
    prime_run: "{{ base_path }}/prime-run"
    phoronix_folder: "{{ base_path }}/phoronix"
    phoronix_test_suite: "{{ phoronix_folder }}/phoronix-test-suite"
    benchmark_result_folder: "../../benchmark_result"

    glmark2_version: 'glmark2-1.4.0'
    namd_version: 'namd-cuda-1.1.1'
    pytorch_phoronix_test_version: "pytorch-1.0.1"
    nvidia_driver_version: "525"
    restart_gdm_service: false
    validate_nvidia_pci_exists: true

    # some Nvidia apt-package are keep being reinstalled by Ansible somehow, slowing down the benchmark process. This option come
    # to skip them to save some time, as long as you're sure that those drivers already installed successfully
    install_nvidia_and_nvcc_drivers: true

    use_namd_github_mirror: true
    namd_github_mirror: "https://github.com/Hzz-Hzz/Tugas-Akhir-OpenStack-LFS/raw/main/namd-download-cache.zip"
    namd_downloaded_mirror_cache_folder: "{{ base_path }}/namd-cache-folder"
    namd_timeout_duration_per_sample: 60  # in second

    ### USER CONFIGURABLE VARS. See README.md
    distro: "ubuntu2004"
    arch: "x86_64"


  tasks:
    - name: ensure base_path folder exists
      ansible.builtin.file:
        path: "{{ base_path }}"
        state: directory
    - name: ensure benchmark_result_folder folder exists
      delegate_to: localhost
      ansible.builtin.file:
        path: "{{benchmark_result_folder}}"
        state: directory
    - name: Perform Benchmark
      import_tasks: perform_benchmark.yaml