### Convert all scripts to linux end-of-line separator
- name: convert all ansible-related file to LF end-of-line
  command: "python3 ./scripts/convert-all-crlf-to-lf.py \"{{parent_directory}}\" 2>&1"
  delegate_to: "localhost"
  register: result


#### DEPENDENCIES
- import_tasks: install_nvidia_smi.yaml

# async download. Please put it after install_nvidia_smi.yaml because install_nvidia_smi.yaml has reboot command that
# may corrupt the async download process
- when: "use_namd_github_mirror"
  block:
    - set_fact:
        namd_github_mirror_location: "{{ base_path }}/namd-mirror.zip"
    - name: ensure benchmark_result_folder folder exists
      ansible.builtin.file:
        path: "{{namd_downloaded_mirror_cache_folder}}"
        state: directory
    - name: Download Phoronix NAMD Github mirror
      ansible.builtin.get_url:
        url: "{{ namd_github_mirror }}"
        dest: "{{ namd_github_mirror_location }}"
        timeout: 4000
      async: 4000
      poll: 0
      register: async_download_ubuntu_image



- import_tasks: install_pexpect.yaml
- import_tasks: download_phoronix.yaml
- import_tasks: create_prime_run.yaml


- set_fact:
    nvidia_track_py_script: "{{ base_path }}/nvidia-smi-track.py"
- name: Upload nvidia-smi-track.py
  become: true
  copy:
    src: ./scripts/nvidia-smi-track.py
    dest: "{{ nvidia_track_py_script }}"
    mode: "0755"


#### TASKS
- import_tasks:
    file: ./benchmark_glmark2.yaml
- import_tasks:
    file: ./benchmark_namd.yaml
- import_tasks:
    file: ./benchmark_pytorch.yaml


